# Spell checker workflow for GitHub Actions using cSpell and using a custom dictionary from VS Code
name: Spell Checker
on:
  # Check the spelling of all commits to the production branch
  push:
    branches:
      - production
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  spell-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install cSpell
        run: npm install -g cspell@latest @cspell/cspell-json-reporter@latest
      - name: Spell Checker
        run: cspell "**/*" --config .vscode/cspell.json --no-progress --no-summary --reporter @cspell/cspell-json-reporter --reporter-options outFile=cspell-results.json
      - name: Upload cSpell Report
        uses: actions/upload-artifact@v4
        with:
          name: cspell-results.json
          path: cspell-results.json
      - name: Send notification to NTFY channel
        run: |
          curl \
            -H "Title: GitHub Actions Spell Checker Report" \
            -H "Authorization: Bearer {{ secrets.NTFY_TOKEN }}" \
            -H "Priority: default" \
            -H "Markdown: yes"  \
            -H "Tags: bell,github-actions,github" \
            -H "Click: {{ github.repository }}/actions/runs/${{ github.run_id }}" \
            -d "A **cSpell Action report** for a GitHub Actions workflow has been generated for the repository '${{ github.repository }}' on branch '${{ github.ref }}' at the date and time of '${{ steps.timestamp.outputs.now }}'." \
            ${{ secrets.NTFY_URL }}
