blank_issues_enabled: false
contact_links:
  - name: Repository Security Issues, Bug Reports, Feature Requests, and General Inquiries
    url: https://monsterspawned.com/contact/
    about: Please report security vulnerabilities, bugs, feature requests, or ask general inquiries here.
